### ISSUE TITLE
Examples.html web page error

### ISSUE THREAD

**Issue by ghost** [cainus/percolator#48]
The example code on the web site has the wrong number of args in the update function of the CRUDCollection. http://percolatorjs.com/examples.html

update : function($, obj, cb)

   should be: 

update : function($, id, obj, cb)

**Comment by cainus** [comment]
Thanks! I guess I forgot to test that part of the examples.  I've fixed the docs in their repo, but it'll have to wait for me to get home tonight to upload them.
