### ISSUE TITLE
Update handler and promise, seems to be broken?

### ISSUE THREAD

**Issue by ghost** [cainus/percolator#49]
I implemented an update method, it has a kind-of-promise type implementation..

The update fails when the CRUDCollection method tries to run $.onJson in the generic update handler.

When my function returns a simple data structure immediately from within my update implementation directly, it works ok.

I'll post my code with a link soon if that would be useful.

**Comment by cainus** [comment]
If I understand you correctly, that's how it's supposed to work.  $.onJson has already been called for you, if you use CRUDCollection's update(), so you shouldn't need to call it again in the update() implementation.  You can just use the object that got passed in to update as the second param.

Let me know if I'm misunderstanding though.  Perhaps some code would shed some light on the problem if so.

**Comment by ghost** [comment]
Sorry Gregg. That was a really poor explanation of the issue i'm having.

I basically used the example code you have and then plugged in (read: hacked) a filesystem based persistence layer, which was based on a  
cache called Node-Simple-Cache. It seems to work ok.

Everything else is working AFAICT and i've followed the pattern you used by implementing the crud functions on the DB object i have.  

This is the error and a util.inspect($) added to the CRUDCollection.js at line 81 where the error is.

For some reason $onJson is undefined and my DB update method never actually gets called.

https://gist.github.com/4333136

Project code here. Note: I've commented out the upsert method in perky.js so it tries to use the update function with a PUT:

https://github.com/therto/Perky/

Creating an object in the store.
 curl -XPOST 127.0.0.1:3001/links/ -d '{ "_id": "2", "tags" : ["hello_2", "world_2"], "url" : "http://www.google.com.au"}'

Updating an object in the store fails when using update but works when using upsert.
curl -XPUT 127.0.0.1:3001/links/2 -d '{ "_id": "2", "tags" : ["hello_2", "world_2"], "url" : "http://www.google.com.au"}'

If there is anything else i can do to help, let me know.

cheers,

**Comment by cainus** [comment]
I cloned your repo and I'm reproducing locally, so it turns out you're not
lying.  ;)  I'll see if I can patch this up tonight.  Thanks for the report
and sorry about the bug.  I was testing upsert() mostly, so I guess
update() got neglected.

BTW, you could use a package.json:

{
      "name": "Perky",
      "description" : "Perky",
      "keywords" : [],
      "version": "0.0.1",
      "private" : true,
      "bugs": {
       "url": ""
      },
      "dependencies": {
          "Percolator" : "0.10.6"
      }
}

G

**Comment by ghost** [comment]
No problems at all.

What is the package.json used for?  

## 

shaun etherton
0433 143 761

**Comment by ghost** [comment]
re: package.json Thanks for the advice, i've added a package.json file now. :)
I thought it was only used for npm publishing. Live and learn! :)

## 

shaun etherton
0433 143 761

**Comment by cainus** [comment]
I'm still working on this... It doesn't seem to fail outside of your example, which was surprising because I don't see a problem with your example either.  At the very least, Percolator should give more obvious errors in these scenarios.

**Comment by cainus** [comment]
I had done some stupid stuff with the incoming request stream that caused this issue.  It should work now.  CRUDCollection.fetch() doesn't take an id parameter anymore though (see http://percolatorjs.com/documentation.html#crudCollection-fetch ).

Also you'll want to use Percolator 0.11.0 to get the fix.

Let me know if that doesn't work, or you see other problems.  Thanks for the heads-up on this!

**Comment by ghost** [comment]
No problem at all. Ill update soon and give it a go. Thanks for sharing your project. :)
