### ISSUE TITLE
Update for detour 1.0.x compatibility

### ISSUE THREAD

**Issue by GordStephen** [cainus/percolator#79]
Really enjoying percolator as a proper REST API framework! Unfortunately, installing dependencies via npm results in broken advanced routing at the moment - 'detour' 0.16.7 has an npm dependency chain issue involving 'walk'. This is fixed in the latest detour v1.0.0 as the walk dependency is eliminated. However, detour v1.0.0 isn't compatible with percolator v1.4.0.

Right now my stop-gap solution is just to manually change the dependency versions in nested package.json files:

percolator -> detour -> walk (forEachAsync '>=2.1.0' -> forEachAsync '~2.1.0')
npm install (in walk)
percolator -> detour -> walk -> forEachAsync (sequence '>=2.1.1' -> sequence '~2.1.1')
npm install (in forEachAsync)

at which point advanced routing (ie server.routeDirectory) works again.

**Comment by cainus** [comment]
Is the problem that walk can't get sequence 2.1.1?  or that it gets an incompatible sequence due to the fuzzy versioning?

Thanks!

**Comment by GordStephen** [comment]
Incompatible sequence - >=2.1.1 in forEachAsync's package.json pulls in v3.0.0.

**Comment by cainus** [comment]
Hey sorry about the slowness fixing this... I've had a pretty busy week.  I'll get on this this weekend though.  Should be pretty easy to fix.

**Comment by cainus** [comment]
I just published 1.4.2, which should fix this.  Let me know if you have any issues with it.  Thanks!

**Comment by GordStephen** [comment]
No, thank you! Did a fresh install today and it worked great, cheers.
