### ISSUE TITLE
broken behavior

### ISSUE THREAD

**Issue by disruptek** [cainus/percolator#91]
Given the following handler...

``` coffeescript
class Test
    authenticate: (request, result, callback) ->
        Test.count = (Test.count or 0) + 1
        callback null

    GET: (request, response) ->
        response.object({count: Test.count}).send()
```

...make repeated requests sequentially.  The first few produce output which corresponds to the counts of requests made previously, as expected.  At the 1590th request, the invocations of `authenticate()` increase to ~9-12 per request.  The output:

``` console
{"count":1582}
{"count":1583}
{"count":1584}
{"count":1585}
{"count":1586}
{"count":1587}
{"count":1588}
{"count":1589}
{"count":1590}
{"count":1593}
{"count":1600}
{"count":1608}
{"count":1618}
{"count":1629}
{"count":1640}
{"count":1651}
{"count":1662}
{"count":1673}
{"count":1684}
...
```

Thanks for percolator, and I hope I can use it.  This issue escaped me in development and now I have completed an API service that I cannot deploy.  :cry: 

edit: This actually seems to be an issue even when not using authentication.
edit: It's an issue in both node 0.10 and 0.11.

**Comment by cainus** [comment]
That sounds absolutely crazy.  Do you have any clue what the issue is with 0.10.26, or why 0.11.12 might fix it?

**Comment by cainus** [comment]
Also, I'd like to see the test script that you're running if possible.

**Comment by disruptek** [comment]
I know, it seems completely bananas.  It's the kind of problem that you look at while you're composing a bug report and think, "I must be missing something obvious."  Actually, I still feel that way.  :smile:

I haven't been working on this stuff since I posted the report, but I'll try to be a little more responsive going forward.  I don't spend much time in front of computers, unfortunately.  I ran into the problem using AWS Elastic Beanstalk, which (natively) supports only 0.10.26, so it's not a problem specific to OS X.  The AWS instance uses nginx in front of node, so it's also not something specific to the curl interaction in my test.

That "test script" is just some bash shell commands, but off the top of my head, I've been doing something like this:

``` bash
X=0
while [ $X -lt 1700 ]; do
    X=`expr $X + 1`
    if ! curl http://localhost:8081/api/1/health/check?x=$X; then
        date
        break
    fi
    # (add newline to output)
    echo
done
```

Again, you can reproduce the problem without using the `authenticate()` definition; a handler as simple as this will demonstrate the issue:

``` coffeescript
class Test
    GET: (request, response) ->
        Test.count = (Test.count or 0) + 1
        response.object({count: Test.count}).send()
```

However, I just discovered that this handler didn't start misbehaving until 1635:

```
{"count":1635}
{"count":1637}
```

Curiouser and curiouser.  Removing code seems to have helped stave off the bug, however shortly.    Perhaps this gives you an idea of the bogus code path?

If possible, please let me know if you can reproduce this.  If so, I will start digging through node bug reports and see if the problem hasn't been solved there.

**Comment by cainus** [comment]
Alright... I rewrote your example in javascript and I tested with a test tool (Charles HTTP debugger), and I'm seeing exactly the same thing in 0.10.28.  I also saw the problem start at about 1635, and interestingly, that's when the server logs started showing 500s as well.  This happens whether I test in concurrent batches of 10, or just serially with a batch size of 1.   Just in case you're curious, this is the stack trace that the domain catches:

```
Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (http.js:689:11)
    at ServerResponse.res.setHeader (/home/cainus/perctest/node_modules/percolator/node_modules/connect/lib/patch.js:59:22)
    at send (/home/cainus/perctest/node_modules/percolator/node_modules/hyperjson-connect/index.js:14:7)
    at json.send (/home/cainus/perctest/node_modules/percolator/node_modules/hyperjson-connect/index.js:65:16)
    at Object.server.route.GET (/home/cainus/perctest/index.js:45:34)
    at callHandlerMethod (/home/cainus/perctest/node_modules/percolator/node_modules/detour/lib/Router.js:179:33)
    at /home/cainus/perctest/node_modules/percolator/node_modules/detour/lib/Router.js:165:14
    at /home/cainus/perctest/node_modules/percolator/lib/Percolator.js:149:17
    at onJsonHelper (/home/cainus/perctest/node_modules/percolator/lib/ContextHelpers/onJson.js:63:3)
    at /home/cainus/perctest/node_modules/percolator/lib/Percolator.js:147:28
```

Soooo... I've got some digging to do, because nothing obvious pops out at me there.  But at least that's a place to start.  I'll play with this more tonight and let you know how it goes.

**Comment by disruptek** [comment]
Thanks for reproducing the issue.  If we could narrow it to the node code, then we can probably create a failing test and get it fixed upstream (or figure out how to work around it).

**Comment by cainus** [comment]
Okay... I think I've got it solved.  I _think_ the bug was only when using `after()`.  Upgrading connect to 3.x.x seems to have solved it.  This means node 0.8 is no longer supported, but I think that's a worthy trade-off.  It should be fixed in Percolator 1.5.0.  Let me know how that works for you, and feel free to close this ticket if it does.  Thanks!

**Comment by disruptek** [comment]
Awesome, thanks very much for the fix!  It doesn't fail the simplified test case, so I think I'll close the ticket and open a new one if necessary, with a new failing test.  I really appreciate the speed with which you solved this.  :smile:

**Comment by disruptek** [comment]
Too soon:

```
{"count":1678}
{"count":1679}
{"count":1681}
{"count":1684}
{"count":1687}
{"count":1690}
{"count":1693}
```

Now it only duplicates the invocations twice, but it's still duping.  Can you confirm this one?

**Comment by cainus** [comment]
Bah... Alright... I can another look tonight.  I had a minimal reproduction that this change solved, so I figured that I had solved completely.  Can you paste me your minimal reproduction code (including the server)?  Coffeescript is fine too if that's what you've got.

**Comment by disruptek** [comment]
Everything above works to reproduce.  I just started running a test to 50k requests and at some point it started duping 4x per request, but I killed it early and don't know when it started failing.  Here's an updated bash script that will answer that question; pass it an argument indicating the number of requests.  It should work on Linux and OS X.

``` bash
#!/usr/bin/env bash
X=0
O=0
while [ $X -lt $1 ]; do
    X=`expr $X + $O + 1`
        R=`curl http://localhost:8081/api/1/health/test?x=$X 2> /dev/null | perl -pe 's/\D+(\d+)\D+/\1/'`
        if [ $? -ne 0 ]; then
                break
        fi
        NO=`expr $R - $X`
        if [ $O -ne $NO ]; then
                printf "request $X yields $R; offset $NO\n"
                O=$NO
    fi
done
```

**Comment by cainus** [comment]
Can I see your node code though?  If I could see what features of the framework you're using, I can start to narrow down the possible issues.  `after()` was definitely one problem, but I imagine there's at least one other.  javascript or coffeescript are fine...

**Comment by disruptek** [comment]
Sure.  Here's a simplified `server.coffee`; it's still almost entirely boilerplate:

``` coffeescript
percolator = require 'percolator'
router = require './router'

serveroptions =
    ip: process.env.LISTEN_IP or '127.0.0.1'
    port: 8081
    protocol: 'http'
    parseBody: false
    autoLink: false

server = new percolator.Percolator serveroptions
callback = (error) ->
    console.log 'ROUTER ERROR', error if error

supported = health: 'health-1'

router __dirname, server, '1', callback, supported

server.listen (error) -> console.log 'LISTEN ERROR', error if error
```

And it uses this little hack to map different API versions to different directories, in `router.coffee`:

``` coffeescript
module.exports = (path, server, version, errors, inputs) ->
    apidir = path + '/api/'
    verdir = '/api/' + version + '/'
    for input, output of inputs
        console.log apidir + output, verdir + input
        server.routeDirectory apidir + output + '/handlers', verdir + input, errors
```

And here's a `health-1/handlers/test.coffee`:

``` coffeescript
class Test
    GET: (request, response) ->
        Test.count = (Test.count or 0) + 1
        console.log Test.count
        response.object({count: Test.count}).send()


exports.handler = new Test()
```

I added a `console.log` so that one can monitor progress by watching the server when using the test script above.  After simplifying to the above code, my output for `./that_test_script.sh 2000` is as follows:

```
request 1729 yields 1730; offset 1
request 1731 yields 1744; offset 13
request 1745 yields 1747; offset 2
```

**Comment by disruptek** [comment]
So, this problem exists in node 0.11 as well; it just fails slightly later.  Do you have any suggestions on where I should start looking?

**Comment by cainus** [comment]
Not yet :/  I didn't get anywhere with it yesterday, but your reproduction is solid.  I'm pretty sure I can track it down today though.

**Comment by cainus** [comment]
Alright... I think my latest commit will fix it.  I was doing some stream pausing and resuming which works entirely differently with new streams (and should be unnecessary if I understand correctly).

Any chance you can try out the latest commit before I publish it?

**Comment by disruptek** [comment]
Just updated to 7c0ae1ca217d9f01dca5524428cc8401d65fdfb7 and ran the test script above with a 10k input, which yielded this:

```
request 1729 yields 1740; offset 11
request 1741 yields 1744; offset 3
request 1745 yields 1747; offset 2
request 2756 yields 2759; offset 3
request 3504 yields 3508; offset 4
request 3509 yields 3512; offset 3
```

Are you seeing the same result with that test script?

**Comment by cainus** [comment]
I simplified your server code a bit, and saw problems before 3000 iterations there, and this fix runs it without problems well above 20,000 iterations.  I'll try getting it closer to your script though.  I've currently just got, which works fine for me:

``` coffeescript
percolator = require 'percolator'

serveroptions =
    ip: process.env.LISTEN_IP or '127.0.0.1'
    port: 8080
    protocol: 'http'
    #parseBody: false
    #autoLink: false

server = new percolator.Percolator serveroptions

count = 0

server.route '/test', {
  GET : (req, res) ->
    count += 1
    console.log count
    #res.object({count: count}).send()
    res.end(JSON.stringify({count : count}))
}

server.listen (error) ->.
  if error
    return console.log 'LISTEN ERROR', error
  console.log "listening on 8080"

```

Anyway... I'll try again with some server code that more closely matches yours.  Sorry about the slowness... This is very weird.

**Comment by disruptek** [comment]
That sounds like great progress, but I can't reproduce it.  I copied your script above and changed only the `->.` to omit the period.  The script fails for me at ~1730.  I am testing this on node 0.10.26 using the 7c0ae1ca217d9f01dca5524428cc8401d65fdfb7 commit.  I stripped out every runtime module (excepting percolator) from my `package.json` and reinstalled all node modules.  Is there anything special about your environment that you may have overlooked?

It seems like we at least have a way to narrow down the scope, as long as one of us can reproduce the problem by adding code, but I'm curious as to why the above works for you and doesn't work for me.  This is what your JavaScript looks like, right?

``` javascript
var count, percolator, server, serveroptions;

percolator = require('percolator');

serveroptions = {
  ip: process.env.LISTEN_IP || '127.0.0.1',
  port: 8080,
  protocol: 'http'
};

server = new percolator.Percolator(serveroptions);

count = 0;

server.route('/test', {
  GET: function(req, res) {
    count += 1;
    console.log(count);
    return res.end(JSON.stringify({
      count: count
    }));
  }
});

server.listen(function(error) {
  if (error) {
    return console.log('LISTEN ERROR', error);
  }
  return console.log("listening on 8080");
});
```

**Comment by cainus** [comment]
Well... with that js you just pasted, I got perfect execution up to 30,000 iterations:

![selection_007](https://cloud.githubusercontent.com/assets/149051/3431665/b5761af8-006c-11e4-87e7-0c4f296b7c51.png)

Then I killed my node_modules dir and git-cloned from the hash I sent you and it fails.  :)  

So I had a change locally that fixed it that I didn't commit/push-up (and then `rm -rf`ed!).  I'll take another look tonight.  If I solved it once, I can solve it again.  ;)

**Comment by cainus** [comment]
Alright... I think I've got it... I integrated connect incorrectly.  Can you give this another shot with the latest commit? (I haven't published yet.)

Sorry about the slowness, and thanks for the help!

**Comment by disruptek** [comment]
It seems you always push a commit the day I'm not checking for one.  :-)

I only have a minute to look at this, but I just tried cb51e9dd9b6bfdcee568097b5575ca418dd3c7bf and while it passes the test script, it seems to be breaking my CORS setup.  I'm using something like this...

``` coffeescript
require 'cors'

server = Percolator()
server.connectMiddleware cors(CORScallback)
```

Should I be doing something different?  I imagine that this also breaks my use of the `response-time` middleware which, trivial as it is, might be easier for you to use when testing...

**Comment by cainus** [comment]
Can you give me more specifics on what problem you're having with that exactly?  Possibly a more specific test case like you provided previously?

Thanks for the testing help too!

**Comment by disruptek** [comment]
Okay, please disregard the "404 on OPTIONS" report -- I guess maybe I had pulled in only the latest commit and not the json-status update?

The new problem is that a POST is simply hanging when I attempt to read the request body using either `request.onBody()` or `request.onJson()`.

Here's an example handler:

``` coffeescript
class Test
    POST: (request, response) ->
        console.log 'calling onJson'
        request.onJson (error, input) ->
            console.log 'onJson callback invoked'
            return console.log error if error
            response.object({onJson: input}).send()


exports.handler = new Test()
```

And here's an example test:

``` console
curl -X POST -d '{hello: "there"}' http://localhost/test
```

And the output is only:

``` console
calling onJson
```

**Comment by cainus** [comment]
I just committed a test for this and it passes... Any clue how yours is different?  https://github.com/cainus/percolator/blob/master/test/Percolator.js#L228

**Comment by disruptek** [comment]
Thanks for the test; it's passing here, but I'm still having trouble with CORS.  I traced the problem above to a typo in an identifier in my latest test server, which is a bizarre problem in and of itself.  I still have the problem with hanging input parsing, but only with my production code.

Let's try closing this issue (again) and I'll open a new one when I get further along with a repeatable test.  Thanks so much for your attention; I'm sure I'm close to making Percolator work in production...
