### ISSUE TITLE
asynchronous authentication for POST no longer working with CORS

### ISSUE THREAD

**Issue by disruptek** [cainus/percolator#93]
Given a simple CORS configuration using `node-cors`...

``` coffeescript
cors = require 'cors'
corsoptions = (request, callback) ->
    options =
        origin: true
        methods: ['GET', 'PUT', 'POST', 'OPTIONS']
        allowedHeaders: ['Content-Type', 'Pragma', 'Cache-Control', 'User-Agent', 'Referer', 'Origin']
    callback null, options
server.connectMiddleware cors(corsoptions)
```

...this handler works fine in 1.4.3 but hangs in 1.5.0 or HEAD...

``` coffeescript
class Test 
    authenticate: (request, result, callback) ->
        setTimeout callback, 2000, null, {}

    POST: (request, response) ->
        console.log 'parsing...'
        request.onJson (error, input) ->
            return console.log 'input error', error if error
            response.object({onJson: input}).send()


exports.handler = new Test()
```

...when exercised via...

``` console
curl -X POST -d '{"hello": "there"}' http://localhost/test
```

To make it work, one can omit CORS by commenting out the `server.connectMiddleware()`, or one can replace the `setTimeout()` call with `callback null, {}` in `authenticate()`.

**Comment by cainus** [comment]
Alright, I'm having a heck of a time reproducing this, but I have a hunch about it, and wonder if you might be able to give the latest a commit a shot (it's not published)?  I've added stream pausing/resuming so that the streaming doesn't happen until/unless onJson is called.

If that still doesn't work, let me know, and we'll have to figure out how I can get this to reproduce better.

Thanks!

**Comment by disruptek** [comment]
It seems to work.  It's hard to overstate how pleased I am to put this behind us.   Thank you, thank you, thank you!

It looks like a similar change went into node-cors recently, and it appears that upgrading to HEAD in either library solves this problem.  In fact, I also had trouble reproducing the issue once I starting jumping around in different versions of the libraries.  In any event, your change is probably desirable, so I'd recommend keeping it until it demonstrates responsibility for another bug. :wink:

**Comment by cainus** [comment]
Thanks for your help too... Your bug reports are the only way I knew that the framework wasn't working in 0.10+, which is a pretty big over-sight.  Feel free to give me a shout anytime if you run into additional difficulties, even if you just want to hit me on email at gregg@caines.ca .
